# Generated by Django 4.2.1 on 2023-06-17 08:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medilab', '0002_faq_gallery_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=264)),
                ('message', models.TextField()),
                ('created_day', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
