# Generated by Django 4.2.1 on 2023-06-20 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medilab', '0005_newletters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newletters',
            old_name='email',
            new_name='email_subscribe',
        ),
    ]
