# Generated by Django 4.2.1 on 2023-06-20 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medilab', '0006_rename_email_newletters_email_subscribe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newletters',
            old_name='email_subscribe',
            new_name='email',
        ),
    ]
