# Generated by Django 4.2.1 on 2023-06-26 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('medilab', '0007_rename_email_subscribe_newletters_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
        ),
    ]
