# Generated by Django 4.2.1 on 2023-06-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medilab', '0008_appointment_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_day',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_day',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
