# Generated by Django 4.2.1 on 2023-06-26 07:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medilab', '0009_alter_appointment_created_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_day',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_day',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
