# Generated by Django 4.2.1 on 2023-06-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreastCancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male')], max_length=50)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('concave_points_mean', models.FloatField()),
                ('area_mean', models.FloatField()),
                ('radius_mean', models.FloatField()),
                ('perimeter_mean', models.FloatField()),
                ('concavity_mean', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Diabetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male')], max_length=50)),
                ('number_of_pregnancies', models.FloatField()),
                ('glucose_conc', models.FloatField()),
                ('blood_pressure', models.FloatField()),
                ('skin_thickness', models.FloatField()),
                ('insulin', models.FloatField()),
                ('bmi', models.FloatField()),
                ('diabetes_pedigree', models.FloatField()),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeartDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male')], max_length=50)),
                ('old_peak', models.FloatField()),
                ('max_heart_rate', models.FloatField()),
                ('exercise_induces_angina', models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No')])),
                ('number_of_major_vessels', models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('type_of_chest_pain', models.IntegerField(blank=True, choices=[(0, 'typical angina'), (1, 'atypical angina'), (2, 'non-anginal pain'), (3, 'asymptomatic')])),
                ('thal', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
